#!/bin/bash
#
# dmenu script to quickly launch vlc
# with a chosen movie together with
# automatically picked subtitles
#
# the movie's file name must be a part
# of the subtitle file name e.g
# movie:
#   /home/user/movies/Casablanca.mkv
# subtitles:
#   /home/user/subtitles/Casablanca - ENG.srt
#
declare -a filmDirectories=(
"/media/films/"
"/media/films/tw/"
)
subDirectory="/media/films/srt/"

for dir in ${filmDirectories[@]}; do
    output=(${dir}*)
    for ((i=0; i<${#output[@]}; i++)); do
        [ -f "${output[$i]}" ] && fullPaths+=("${output[$i]}")
    done
done

declare -A indexes
for ((i = 0; i < ${#fullPaths[@]}; i++)); do
    indexes[$(echo ${fullPaths[$i]} | awk '{n=split($0,a,"/"); print a[n]}' | sed 's/\....$//')]="$i"
done

chosenTitle=$(printf '%s\n' "${!indexes[@]}" | dmenu -l 7) || exit 0
movieIndex=${indexes[$chosenTitle]}

movie=${fullPaths[$movieIndex]}
subs=$(find $subDirectory -iname "*$chosenTitle*" | head -1)

vlc "$movie" --sub-file "$subs" &> /dev/null &
