#!/bin/sh
#
# choose the config file to edit
#
EDITOR="alacritty -e vim"

declare -a options=(
"alacritty - $HOME/.config/alacritty/alacritty.yml"
"dunst - $HOME/.config/dunst/dunstrc"
"picom - $HOME/.config/picom.conf"
"qtile - $HOME/.config/qtile/config.py"
"ranger - $HOME/.config/ranger/rc.conf"
"vim - $HOME/.vimrc"
"zsh - $HOME/.zshrc"
"conky - $HOME/.config/conky/conky.conf"
"xprofile - $HOME/.xprofile"
)

choice=$(printf '%s\n' "${options[@]}" | dmenu -l 7) || exit 0
$EDITOR "$(echo $choice | awk '{print $NF}')"
