#!/bin/bash
#
# dmenu script to quickly launch vlc
# with a chosen movie together with
# automatically picked subtitles
#
# the movie's file name must be a part
# of the subtitle file name e.g
# movie:
#   /home/user/movies/Casablanca.mkv
# subtitles:
#   /home/user/subtitles/Casablanca - ENG.srt
#
declare -a filmDirectories=(
"/media/films/"
"/media/films/tw/"
)
subDirectory="/media/films/srt/"

for dir in ${filmDirectories[@]}; do
    output=(${dir}*)
    for ((i=0; i<${#output[@]}; i++)); do
        [ -f "${output[$i]}" ] && fullPaths+=("${output[$i]}")
    done
done

for ((i = 0; i < ${#fullPaths[@]}; i++)); do
    titles[$i]="$i -  $(echo ${fullPaths[$i]} | awk '{n=split($0,a,"/"); print a[n]}' | sed 's/\....$//')"
done

choice=$(printf '%s\n' "${titles[@]}" | dmenu -l 7) || exit 0
movieIndex=$(echo $choice | awk '{print $1}')
title=$(echo ${titles[$movieIndex]} | sed 's/^[0-9]* - //')

movie=${fullPaths[$movieIndex]}
subs=$(find $subDirectory -iname "*$title*" | head -1)

vlc "$movie" --sub-file "$subs" &
